### ISSUE TITLE
Regular expressions in labels

### ISSUE THREAD

**Issue by jplitza** [gepaplexx/multena-proxy#140]
It's currently kind of possible to use patterns, but not consistently.

When a user is allowed access to more than one label value, the values are always used as regular expressions (concatenated with `|`), in which case the provided label values are not escaped and interpreted as regular expressions.

However, when the tenant label is specified in the incoming query, it is checked for *equality* with an allowed value (regular expression).

So imagine the following:
```yaml
# labels.yaml
'DevOps':
    '.*-develop': true
    'monitoring': true
'Developers':
    '.*-develop': true
```
```yaml
# config.yaml
web:
  loki:
    tenant_label: namespace
```

The empty query will work as expected for DevOps, returning results for `{namespace=~"monitoring|.*-develop"}`. As will the query `{namespaces=~".*-develop"}` (which is not translated at all).

But the query `{namespace="app-develop"}` will not, throwing "unauthorized label app-develop".

Neither will the empty query work for Developers, since it is translated to `{namespace=".*-develop"}` (not `=~`).
