### ISSUE TITLE
Allow defining arbitrary labels for users and groups

### ISSUE THREAD

**Issue by smauermann** [gepaplexx/multena-proxy#93]
I think it would come really handy if we could define arbitrary labels an entity would be allowed to read. Is this something you have thought about and do you see any issues with this approach

```yaml
user1:
  namespace: foo
  team: foo
  app: foo-bar

user2:
  namespace: bar
  service: bar
```
